name: flutter_disable_screenshot
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/appinioGmbH/flutter_packages
repository: https://github.com/appinioGmbH/flutter_packages/tree/main/packages/flutter_disable_screenshot

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appinio.screenshot
        pluginClass: ScreenshotPlugin
      ios:
        pluginClass: ScreenshotPlugin
